mysite/login/urls.py
from django.conf.urls import url
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^registration$', views.registration, name='registration'),
    url(r'^activated_account$', views.activated, name='activated_account$'),
    path('account/', include('django.contrib.auth.urls'), name = 'login'),
    path('account/', include('django.contrib.auth.urls'), name=' logout'),
    path('cost/new/', views.add_pers_cost, name='add_pers_cost'),
    path('cost/remove/', views.rem_pers_cost, name='rem_pers_cost'),
    path('cost/costAdd/', views.add_cost, name='add_cost'),
    path('cost/cosSys/', views.cost_system, name='cost_system'),
    path('Inc/new/', views.add_pers_inc, name='add_pers_inc'),
    path('Inc/remove/', views.rem_pers_inc, name='rem_pers_inc'),
    path('Inc/incAdd/', views.add_income, name='add_income'),
    path('Inc/incSys/', views.income_system, name='income_system'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls'))]

mysite/login/models.py
import psycopg2
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Cost_category(models.Model):
    category_name = models.CharField(max_length=50, primary_key=True)

    def __str__(self):
        return self.category_name

class Personal_cost_category(models.Model):
    person_category_name = models.CharField(max_length=50, blank=True, null=True)
    user_login = models.ForeignKey(User, to_field='username', on_delete=models.CASCADE)

class Cost_system1(models.Model):
    date = models.DateField(default=timezone.now)
    sum = models.DecimalField(max_digits=20, decimal_places=2)
    login = models.ForeignKey(User, to_field='username', max_length=50, on_delete=models.CASCADE)
    id_category_cost = models.ForeignKey(Cost_category, max_length=50, blank=True, null=True, on_delete=models.CASCADE)
    id_personal_category_cost = models.CharField(max_length=50, blank=True, null=True)

class Income_category(models.Model):
    category_name = models.CharField(max_length=50, primary_key=True)

    def __str__(self):
        return self.category_name

class Personal_income_category(models.Model):
    person_category_name = models.CharField(max_length=50,blank=True, null=True)
    user_login = models.ForeignKey(User,to_field='username', on_delete=models.CASCADE)

class Income_system(models.Model):
    date = models.DateField(default=timezone.now)
    sum = models.DecimalField(max_digits=20, decimal_places=2)
    login = models.ForeignKey(User, to_field='username', max_length=50,on_delete=models.CASCADE)
    id_category_income = models.ForeignKey(Income_category, max_length=50, blank=True, null=True, on_delete=models.CASCADE)
    id_personal_category_income = models.CharField(max_length=50, blank=True, null=True)

mysite/login/forms.py
from .models import Personal_cost_category, Cost_system1, Personal_income_category, Income_system
from django import forms


class Personal_cost_category_forms(forms.ModelForm):
    class Meta:
        model = Personal_cost_category
        fields = ('person_category_name',)


class Cost(forms.ModelForm):
    class Meta:
        model = Cost_system1
        fields = ('date', 'sum', 'id_category_cost', 'id_personal_category_cost',)

class Time(forms.Form):
    renewal_date = forms.DateField()
    renewal_date2 = forms.DateField()

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        return data

    def clean_renewal_date2(self):
        data = self.cleaned_data['renewal_date2']
        return data

class Personal_income_category_forms(forms.ModelForm):
    class Meta:
        model = Personal_income_category
        fields = ('person_category_name',)

class Income(forms.ModelForm):
    class Meta:
        model = Income_system
        fields = ('date', 'sum', 'id_category_income', 'id_personal_category_income',)

mysite/login/views.py
from audioop import reverse

from django.contrib.auth.decorators import login_required

from .viewsCost import *
from .viewsIncome import *

from datetime import datetime

import psycopg2
from django.http import HttpRequest, HttpResponseRedirect

from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


conn = psycopg2.connect(database="django3", user="postgres",
                        password="postgres", host="localhost", port=5432)

def index(request):
    list_articles = User
    context = {'name': list_articles}
    template = 'login/mainHome.html'
    return render(request, template, context)


def detail_page(request):
    template = 'login/registration/login.html'
    return render(request, template)


def registration(request):
    """Renders the registration page."""
    assert isinstance(request, HttpRequest)
    if request.method == "POST":  # после отправки формы
        regform = UserCreationForm(request.POST)
        if regform.is_valid():  # валидация полей формы
            reg_f = regform.save(commit=False)  # не сохраняем автоматически данные формы
            reg_f.is_staff = False  # запрещен вход в административный раздел
            reg_f.is_active = True  # активный пользователь
            reg_f.is_superuser = False  # не является суперпользователем
            reg_f.date_joined = datetime.now()  # дата регистрации
            reg_f.last_login = datetime.now()  # дата последней авторизации
            reg_f.save()  # сохраняем изменения после добавления данных
            # переадресация на главную страницу после регистрации

            return render(request, 'login/mainHome.html')
    else:
        regform = UserCreationForm()  # создание объекта формы для ввода данных нового пользователя
        assert isinstance(request, HttpRequest)
    return render(
        request,
        'login/registration.html',
        {
            'regform': regform,  # передача формы в шаблон веб-страницы
            'year': datetime.now().year,
        }
    )

def activated(request):
    user = User.objects.get(username=request.user.username)
    context = {'name': user,
               'ex' : 'Ok' }
    template = 'login/mainHomeAuto.html'
    return render(request, template, context)

mysite/login/templates/login/Cost_system.html
<!doctype html>
{% extends "login/Wrapper.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Your costs</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body>

{% block content %}

<script>
    document.write(new Date());
</script>
<br>
<h1>Your costs </h1>

<h3>Number of Payments this Week</h3>
{% load googlecharts %}

<div id="count_graph" style="width: 95%">

    {% googlecharts %}
    {% data values "count" %}
    {% col "string" "Date" %}"{{ val|date:"j M" }}"{% endcol %}
    {% col "number" "# of payments" %}{{ val}}{% endcol %}
    {% enddata %}

    {% options %}
    kind: "LineChart",
    options: {
    backgroundColor: "#f9f9f9",
    colors: ["#09f"],
    gridlineColor: "#ddd",
    vAxis: {minValue: 0},
    chartArea: {left: 70, }
    }
    {% endoptions %}

    {% graph "count_graph" "count" %} {# используем опции по умолчанию #}
    {% endgooglecharts %}
</div>
<br>

<h3>Enter the time period of interest</h3>

<form method="POST" class="post-form">

    <table>
        {% csrf_token %}
        {{ form }}
        <input id="id_renewal_date" name="renewal_date" type="text" value="Year-Month-Day" required/>
        <input id="id_renewal_date2" name="renewal_date2" type="text" value="Year-Month-Day" required/>
        <br/>
    </table>
    <br>
    <button type="submit" class="btn-default" style="margin-left: 13%">Choose day</button>

    <br>
    <br>
    {% csrf_token %}
    <table border="1" width="95%" cellpadding="5" style="margin-left: 2.5%">
        <tr>
            <th> Date</th>
            <th> The amount</th>
            <th> Spent on</th>
        </tr>
        {% for post in posts %}
        <td>{{ post.date }}</td>
        <td>{{ post.sum }}</td>
        {%if post.id_category_cost %}
        <td>{{post.id_category_cost}}</td>
        {%else %}
        <td>{{ post.id_personal_category_cost}}</td>
        {% endif %}
        <tr></tr>
        {% endfor %}
    </table>
</form>

    {% endblock %}
</body>
</html>

mysite/login/templates/login/Income_system.html
<!doctype html>
{% extends "login/Wrapper.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Your income</title>
     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <style>
        #count_graph {
            max-width: 80%;
        }
    </style>
</head>
<body>
{% block content %}

<script>
    document.write(new Date());
</script>
<br>

<h1>Your income </h1>

<h3>Number of Payments this Week</h3>
{% load googlecharts %}
<div id="count_graph" style="width: 95%">
{% googlecharts %}
    {% data values "count" %}
    {% col "string" "Date" %}"{{ val|date:"j M" }}"{% endcol %}
    {% col "number" "# of payments" %}{{ val}}{% endcol %}
    {% enddata %}

    {% options %}
    kind: "LineChart",
    options: {
    backgroundColor: "#f9f9f9",
    colors: ["#09f"],
    gridlineColor: "#ddd",
    vAxis: {minValue: 0},
    chartArea: {left: 50}
    }
    {% endoptions %}

    {% graph "count_graph" "count" %} {# используем опции по умолчанию #}
    {% endgooglecharts %}

</div>
<br>
<h3>Enter the time period of interest</h3>
<form method="POST" class="post-form" >
    <table>
        {% csrf_token %}
        {{ form }}
        <input id="id_renewal_date" name="renewal_date" type="text" value="Enter date" required/>
        <input id="id_renewal_date2" name="renewal_date2" type="text" value="Enter date" required/>
        <br/>
    </table>
<br>
    <button type="submit" class="save btn btn-default" style="margin-left: 13%">choose day</button>
    <br>
    <br>
    {% csrf_token %}
    <table border="1" width="95%" cellpadding="5" style="margin-left: 2.5%">
        <tr>
            <th> Date</th>
            <th> The amount</th>
            <th> Income from</th>
        </tr>
        {% for post in posts %}
        <td>{{ post.date }}</td>
        <td>{{ post.sum }}</td>
        {%if post.id_personal_category_income %}
        <td>{{post.id_personal_category_income}}</td>
        {%else %}
        <td>{{ post.id_category_income_id}}</td>
        {% endif %}
        <tr></tr>
        {% endfor %}
    </table>
</form>
{% endblock %}
</body>
</html>

mysite/login/templates/login/add.html
<!doctype html>
{% extends "login/Wrapper.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>New category costs</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body>
{% block content %}
<h1>Add New Personal Category </h1>

<p>Your categories now:
{% for post in form2 %}
<strong> {{ post.person_category_name }}; </strong>
    {% endfor %}</p>

<h3>Add a new category</h3>
{% if exp == '1' %}
<p style="color: #c90202">This category already exists. Add a new category! </p>
{% elif exp == '0'%}
<p style="color: #c90202">The fields with categories must not be empty!</p>
{% endif %}

<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default" style="margin-left: 3%">Save</button>
</form>
{% endblock %}
</body>
</html>

mysite/login/templates/login/addCost.html
<!doctype html>
{% extends "login/Wrapper.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Add costs</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body>
{% block content %}

<script>
    document.write(new Date());
</script>
<br>
<h1>Add cost </h1>
<form method="POST" class="post-form">
    {% csrf_token %}
    Date: {{ form.date }}
    <br>
    <p>
        Sum: {{ form.sum }}
    </p>
    <p>
        Usually categories: {{ form.id_category_cost }}
    </p>

    <p>The following categories are available to you:

    {% for post in form2 %}
    <strong> {{ post.person_category_name }}; </strong>
    {% endfor %}
    </p>
    <p>
        Your categories: {{ form.id_personal_category_cost }}
    </p>
    {% if exp == '1' %}
    <p style="color: #c90202">You cannot use 'usually categories' and 'your categories' at the same time. Choose one
        thing! </p>
    {% elif exp == '0'%}
    <p style="color: #c90202">The fields in categories must not be empty!</p>
    {% elif exp == '-1'%}
    <p style="color: #c90202">Oops ... Polly did not find such a category</p>
    {% endif %}

    <button type="submit" class="save btn btn-default" style="margin-left: 3%">Save</button>
</form>

<br>
<h3>Want to add your category or remove unnecessary?</h3>
<div>
    <a class="btn-default" href="{% url 'add_pers_cost' %}">Add new category cost</a>
    <a class="btn-default" href="{% url 'rem_pers_cost' %}">Delete your category cost</a>
</div>
{% endblock %}
</body>
</html>

mysite/login/templates/login/addInc.html
<!doctype html>
{% extends "login/Wrapper.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Add income</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body>
{% block content %}
<script>
    document.write(new Date());
</script>
<br>
<h1>Add income </h1>
<form method="POST" class="post-form">
    {% csrf_token %}
    Date: {{ form.date }}
    <br>
    <p>
        Sum: {{ form.sum }}
    </p>
    <p>
        Usually categories: {{ form.id_category_income }}
    </p>

    <p>The following categories are available to you:

    {% for post in form2 %}
    <strong> {{ post.person_category_name }}; </strong>
        {% endfor %}</p>
    <p>
        Your categories: {{ form.id_personal_category_income }}
    </p>
    {% if exp == '1' %}
    <p style="color: #c90202">You cannot use 'usually categories' and 'your categories' at the same time. Choose one
        thing! </p>
    {% elif exp == '0'%}
    <p style="color: #c90202">The fields in categories must not be empty!</p>
    {% elif exp == '-1'%}
    <p style="color: #c90202">Oops ... Polly did not find such a category</p>
    {% endif %}

    <button type="submit" class="save btn btn-default" style="margin-left: 3%">Save</button>
</form>
<br>
<h3>Want to add your category or remove unnecessary?</h3>
<div>
    <a class="btn-default" href="{% url 'add_pers_inc' %}">Add new category income</a>
    <a class="btn-default" href="{% url 'rem_pers_inc' %}">Delete your category income</a>
</div>
{% endblock %}

</body>
</html>

mysite/login/templates/login/addIncPers.html
<!doctype html>
{% extends "login/Wrapper.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>New category income</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<p>
{% block content %}
<h1>Add New Personal Category </h1>
<p>
    Your categories now:
    {% for post in form2 %}
    <strong> {{ post.person_category_name }}; </strong>
    {% endfor %}
<h3>Add a new category</h3></p>

{% if exp == '1' %}
<p style="color: #c90202">This category already exists. Add a new category! </p>
{% elif exp == '0'%}
<p style="color: #c90202">The fields with categories must not be empty!</p>
{% endif %}

<form method="POST" class="post-form" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default" style="margin-left: 3%">Save</button>
</form>
{% endblock %}
</body>
</html>

mysite/login/templates/login/mainHome.html
<!doctype html>
{% extends "login/Wrapper.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Main</title>
    <link rel="stylesheet" href="{% static 'css/wrapp.css' %}">
</head>
<body>
{% block content %}
<br>
<h2>Hi, welcome to CheckPollyMoney</h2>
<p>We can help you track your cash flow. Your life will be <b>easier!</b></p>
<div class="container mt-4">
    <a class="btn-default" href="{%url 'login' %}">Login</a>
    <p><a class="btn-default" href="{% url 'registration' %}">Registration</a></p>
</div>
{% endblock %}
</body>
</html>

mysite/login/templates/login/mainHomeAuto.html
<!doctype html>
<html lang="en">
<head>
    {% extends "login/Wrapper.html" %}
    {% load static %}
    <title>CheckPollyMoney</title>
  </head>
<body>
{% block content %}
<br>
<hr style="width: 95%">
<br>
<div class="page-header">
    Your Costs: <a class="btn-default" href="{% url 'cost_system' %}">View my expenses</a>
    <a class="btn-default" href="{% url 'add_cost' %}">Edit costs</a>
</div>
<hr style="width: 95%">
<br>
<div class="page-header">
    Your Income: <a class="btn-default" href="{% url 'income_system' %}">View my income</a>
    <a class="btn-default" href="{% url 'add_income' %}">Edit income</a>
</div>
<hr style="width: 95%">

{% endblock %}
</body>
</html>

mysite/login/templates/login/registration.html
<!doctype html>
<html lang="en">
<head>
    {% extends "login/Wrapper.html" %}
    {% load static %}
    <meta charset="utf-8">
    <title>registration</title>
</head>
<body>
{% block content %}
<h2>User registration</h2>
<form method="POST">
    {% csrf_token %}
    <div>
        {{ regform.as_p }}
        <button type="submit" class="save btn btn-default" style="margin-left: 3%"> Registration</button>
    </div>
</form>
{% endblock %}

</body>
</html>

mysite/login/templates/login/removePersonalCatForCost.html
<!doctype html>
{% extends "login/Wrapper.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Delete category costs</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body>
{% block content %}
<h1>Remove Personal Category </h1>
<p>Your categories now:
{% for post in form2%}
<strong> {{ post.person_category_name }}; </strong>
{% endfor %}
</p>
<h4>Remove unwanted category from your list</h4>
{% if exp == '0'%}
<p style="color: #c90202">The field must not be empty!</p>
{% endif %}
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default" style="margin-left: 3%">Delete</button>
</form>
{% endblock %}
</body>
</html>

mysite/login/templates/login/removePersonalCatForInc.html
<!doctype html>
{% extends "login/Wrapper.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Delete category income</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body>
{% block content %}
<h1>Remove Personal Category </h1>
<p>Your categories now:
{% for post in form2 %}
<strong> {{ post.person_category_name }}; </strong>
    {% endfor %}</p>
<h3>Remove unwanted category from your list</h3>
{% if exp == '0'%}
<p style="color: #c90202">The field must not be empty!</p>
{% endif %}
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default" style="margin-left: 3%">Delete</button>
</form>
{% endblock %}
</body>
</html>

mysite/login/templates/login/wrapper.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../static/css/wrapp.css" type="text/css"/>
</head>
<body>


<header class="Up">
    <a class="MainSubsribe" href="{% url 'activated_account$' %}">CheckPollyMoney</a>
    <span style="margin-left: 55%;">
    {% if user.is_authenticated and ex == 'Ok' %}
    Hello, {{user.username}}
    <a class="btn-default" style="margin-left: 1%" href="{% url 'logout' %}">Exit</a>
    {% endif %}
    </span>
</header>
<div class="mainContent">
    {% block content %}
    {% endblock %}
</div>
<footer>
    <b>Copyright © 2020 Polytech peter the great</b>
    <address>Saint-petersburg, Russia.</address>
</footer>
</body>
</html>